# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeGame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_content', models.TextField(default='', null=True)),
                ('news_data', models.DateField(max_length=30)),
                ('editor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(max_length=100)),
                ('picture_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100)),
                ('video_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_content',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='number_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='number_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='game_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeGame.Game'),
        ),
        migrations.AddField(
            model_name='picture',
            name='game_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeGame.Game'),
        ),
    ]
