# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeGame', '0002_auto_20190313_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='picture_name',
        ),
    ]
