# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeGame', '0003_remove_picture_picture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='game_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WeGame.Game'),
        ),
        migrations.AlterField(
            model_name='video',
            name='game_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WeGame.Game'),
        ),
    ]
