# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(null=True, upload_to='profilePictures'),
        ),
    ]
